import { Order } from "./App";

export const ordersData: Order[] = [
    {
      id: 1,
      date: "2024-04-05",
      client: "ООО Ромашка",
      carrier: "Перевозчиков Пётр",
      phone: "123-456-789",
      comments: "Просьба позвонить заранее",
      status: "новый",
      atiCode: "12345",
    },
    {
      id: 2,
      date: "2024-04-05",
      client: "АО Яхонт",
      carrier: "Перевозчиков Пётр",
      phone: "123-456-789",
      comments: "Просьба позвонить заранее",
      status: "новый",
      atiCode: "12346",
    },
    {
      id: 3,
      date: "2024-04-05",
      client: "ООО Сфера",
      carrier: "Перевозчиков Пётр",
      phone: "123-456-789",
      comments: "Просьба позвонить заранее",
      status: "в работе",
      atiCode: "12347",
    },
    {
      id: 4,
      date: "2024-04-05",
      client: "ИП Иванов И.И",
      carrier: "Перевозчиков Пётр",
      phone: "123-456-789",
      comments: "Просьба позвонить заранее",
      status: "в работе",
      atiCode: "12348",
    },
    {
      id: 5,
      date: "2024-04-05",
      client: "ИП Сидоров В.П.",
      carrier: "Перевозчиков Пётр",
      phone: "123-456-789",
      comments: "Просьба позвонить заранее",
      status: "завершено",
      atiCode: "12349",
    },
  ];